load('laplacebndHom.mat','AenvNoHom','AenvHom','srange');
load('laplacebndHomA.mat','AenvHomA');
load('laplacebndHomB.mat','AenvHomB');
AenvProven=11./(1+11*srange);


loglog( 1./srange,10*AenvProven.*srange,'g',...
    1./srange,10*AenvHomB.*srange,'r-.',...
    1./srange,10*AenvHom.*srange,'r:',...
    1./srange,10*AenvHomA.*srange,'r--',...
    1./srange,10*AenvNoHom.*srange,'r-',...
    'LineWidth',2);
ylim([1e-2 50]);
xlabel('Mean recall time, $\tau$','Interpreter','latex','FontSize',16);
ylabel('Recognition performance, $\overline{\mathrm{SNR}}(\tau)$','Interpreter','latex','FontSize',16);
legend({'Proven envelope',...
    'Basic constraints',...
    'Topology constraints',...
    'All constraints',...
    '$\mathbf{Q}=0$'},...
    'Location','southwest','Interpreter','latex','FontSize',16);