
load('laplacebnd12.mat','AenvAll','srange');
load('laplacebndChainA12.mat','AenvChains');

AenvProven=11./(1+11*srange);


loglog( 1./srange,100*AenvProven.*srange,'g',...
    1./srange,100*AenvAll.*srange,'r:',...
    1./srange,100*AenvChains.*srange,'r-',...
    'LineWidth',2);
%     1./srange,100*AenvHomC.*srange,'r--',...
ylim([1e-1 500]);
xlabel('Mean recall time, $\tau$','Interpreter','latex','FontSize',16);
ylabel('Recognition performance, $\overline{\mathrm{SNR}}(\tau)$','Interpreter','latex','FontSize',16);
title('Numerical envelopes','Interpreter','latex','FontSize',20);
legend({'Proven envelope',...
    'Numeric: all topologies',...
    'Numeric: serial topology',...
    },...
    'Location','southwest','Interpreter','latex','FontSize',16);