function [ q ] = StickySerialLaplaceTrans( s, numstates )
%q=STICKYSERIALLAPLACEENVTRANS(s,numstates) transition rate for maximum
%Laplace transform of SNR curve for sticky serial model
%   q         = transition rate from end state
%   s         = inverse timescale, Laplace transform parameter
%   numstates = # states

alpha = 1+s + sqrt(s.*(s+2));

q = ((-1)+alpha).*(alpha+(-1).*alpha.^numstates).*(alpha.^4+ ...
  alpha.^(2.*numstates)+2.*alpha.^(2+numstates)+alpha.^(2+( ...
  1/2).*numstates).*(2+(-4).*alpha+((-1)+alpha).*numstates)+ ...
  alpha.^(1+(3/2).*numstates).*((-4)+2.*alpha+numstates+(-1).* ...
  alpha.*numstates)).^(-1).*(alpha.^2+(-2).*alpha.^(1+(1/2).* ...
  numstates)+alpha.^numstates+alpha.^((1/4).*(2+numstates)).*( ...
  4.*alpha.^(1+(1/2).*numstates)+alpha.^numstates.*((-2).* ...
  alpha+((-1)+alpha).*numstates)+alpha.*((-2)+numstates+(-1).* ...
  alpha.*numstates)).^(1/2));



end

